name: p3l1

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Setup AWS Cli
        run: sudo apt-get install -y awscli

      - name: Deploy to S3
        run: aws s3 cp out/ s3://p3l1/ --recursive
          echo ${{ secrets.MY_PASSWORD }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
