name: p3l1

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/checkout@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Setup AWS Cli
        run: sudo apt-get install -y awscli
